### PR TITLE
Bump paint-rails to use paint 0.6.7

### PR DESCRIPTION
**Pull request by daemonsy**
## What's up?

This updates the rails gem to use paint 0.6.7

@deioo does it this reflect the recent changes made to paint? I basically just a rake task to pull in changes, good to have your :eyes: on this.

@katherinlaine can you review this?

### CODE REVIEW

**Comment by deioo** [comment]
Yes, we're probably going to update paint a few more times in the next few days, but feel free to pull the 0.6.7 version, it has the latest typography and button changes and it's stable.

**Comment by katherinlaine** [comment]
:+1: looks good to me. I'm interested to see the changes! Also, @daemonsy, how often does it make sense to update the gem? Each time there is a minor update?

**Comment by deioo** [comment]
Probably now and then it should be fine, if you find any bugs with the existing components feel free to open issues so we can fix them.

**Comment by daemonsy** [comment]
@katherinlaine ideally we should have an automated tasks always updating it without human intervention, backed by tests. But right now, I'm updating it when I need to use it =P

**Comment by deioo** [comment]
Btw, feel free to use 0.6.8 in case you plan to use the vertical-align component.

**Comment by daemonsy** [comment]
ok @deioo I have great timing -_-

**Comment by daemonsy** [comment]
Anyway, I tried using the gem locally in Octopus. Works fine. Gonna push it to rubygems.

**Pull request merged**
